resources:
  repositories:
  - repository: ApplicationRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/ApplicationRepo
    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: ApplicationRepo

- script: dir $(Build.SourcesDirectory)

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Code'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Code'
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
