resources:
  repositories:
  - repository: ApplicationRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/ApplicationRepo
    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: ApplicationRepo

- script: dir $(Build.SourcesDirectory)
